// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqeQyA9SGWI3sjdkMqag0DJze5HfO8lTk',
    appId: '1:581972105215:web:7ebec376b463d8d2edb9ca',
    messagingSenderId: '581972105215',
    projectId: 'chatapp-600f5',
    authDomain: 'chatapp-600f5.firebaseapp.com',
    storageBucket: 'chatapp-600f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3bVWWrXBGJl4s-b8ME2yVxjrGdFvuLyg',
    appId: '1:581972105215:android:c72a95bebf33b7c3edb9ca',
    messagingSenderId: '581972105215',
    projectId: 'chatapp-600f5',
    storageBucket: 'chatapp-600f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFsVIC4Kh9YO1uKI9aTafv96PkzoAzAVY',
    appId: '1:581972105215:ios:7e1cae1b9b4a7f11edb9ca',
    messagingSenderId: '581972105215',
    projectId: 'chatapp-600f5',
    storageBucket: 'chatapp-600f5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFsVIC4Kh9YO1uKI9aTafv96PkzoAzAVY',
    appId: '1:581972105215:ios:9c8e36b28b8db572edb9ca',
    messagingSenderId: '581972105215',
    projectId: 'chatapp-600f5',
    storageBucket: 'chatapp-600f5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
